### ISSUE TITLE
Create Ugly/Negative Test Vectors

### ISSUE THREAD

**Issue by haudiobe** [Dash-Industry-Forum/Test-Cases#1]
Ugly/Negative Test Vectors
Waqar/Thomas create test vector that tests Essential Property and @profiles attribute
All to collect additional test cases and vectors to address functionality for forward compatibilty
Use Cases for ugly test vectors:
multiple profiles where the client does pruning
Usage of the EssentialDescriptor, for example using different schemes
Using the ContentProtection Element
Waqar/Thomas create test content

**Comment by waqarz** [comment]
Also add the test case to test cases document.

**Comment by waqarz** [comment]
The ones already done:
http://dashif.org/testvectors/#NEGE
http://dashif.org/testvectors/#NEGC
