### ISSUE TITLE
Multi-Period On-Demand with presentationTime Offset

### ISSUE THREAD

**Issue by haudiobe** [Dash-Industry-Forum/Test-Cases#2]
Hi Thomas,
I am trying to figure out how to accommodate OnDemand profile with XLink-based ad insertion. Let’s say, you have something like this in your first period:

<Representation id="movie 1" codecs="avc1.42000C" width="304" height="176" startWithSAP="1" bandwidth="46971">
                <BaseURL>movie.mp4</BaseURL>
                <SegmentBase indexRange="1595-7886" indexRangeExact="true">
                                <Initialization range="0-1594"/>
                </SegmentBase>
</Representation>

You want to have movie.mp4 be the same file for the whole asset, but have different parts of it in different periods. I.e., have the same BaseURL in all periods but start playout from different subsegment in different period.

I think understand how to do this with SegmentList (using SegmentUrlType@mediaRange), but this is incompatible with OnDemand profile and with DASH264.

Can @presentationTimeOffset be useful here (i.e., indicate at which point in time the presentation starts in the period)?

What do you think?

Alex.

**Comment by haudiobe** [comment]
Alex,

I am working with Waqar on exactly this issue as well. We need to fix this problem and create some test content.
We also need this for other purposes.

Here is how it works:
- You need to split the mp4 file into let’s say 4 pieces
- This requires that you do some modifications, namely:
  - the segment index needs to be parsed and we create 4 "equal size" segments from it
  - we generate a new Segment Index for each of the four segments (basically the same as the one before, but the offsets need to be changed)
  - We add the movie header to all of them
  - This needs to be done for each Representation and media componentent and each Adaptation Set
  - Now the Periods need to be generated and you need the presentationTimeOffset to be added
- We likely also want to address the issue of Period Continuity in this case

Waqar, do you need more information and should I write a document that explains the exact details? I think I should as we have the questions in different contexts.

Thomas

**Comment by waqarz** [comment]
Waqar: create test vectors for the test cases above
Robustness: Add Periods without ads, just continuous content. Make sure that client plays content continuously if signalling is provided
Ad Insertion: we need to 1 main content and 1 ad content (possibly targeted) => details are up to ad insertion group
Add/remove Representations to force switch => client plays continuously
Add/remove Adaptation Sets for reselection, e.g. change language or add/remove subtitles
Robustness: Add empty period in order to emulate failure at server (need to check details)
